### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by dibyendu415** [JGEC-Winter-of-Code/JWoC_Algorithms#14]

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java Language

**Comment by SubhradeepSS** [comment]
I made a PR fixing this issue.
Can u assign me this?

**Comment by richard937** [comment]
@parjanyaacoder go-ahead

**Comment by richard937** [comment]
@SubhradeepSS he claimed it first

**Comment by himanshusharma89** [comment]
I would like to work on it on C and C++ language

**Comment by saurav-skl** [comment]
I would like to work on these in C++,C , python language.

**Comment by richard937** [comment]
then @saurav-skl you do it in Python and @himanshusharma89 you in c/c++

**Comment by himanshusharma89** [comment]
I have created Selection Sort Algo in C and C++. Check PR #2.
