### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by dibyendu415** [JGEC-Winter-of-Code/JWoC_Algorithms#15]

**Comment by SubhradeepSS** [comment]
I made a PR fixing this issue.
Can u assign me this?

**Comment by ank1traj** [comment]
Assign this to me.

**Comment by himanshusharma89** [comment]
I would like to work on this in C and C++ language.

**Comment by Marcus-auz** [comment]
Assign this to me since no one is assigned for c++ lang
