### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by dibyendu415** [JGEC-Winter-of-Code/JWoC_Algorithms#16]

**Comment by SubhradeepSS** [comment]
I made a PR fixing this issue.
Can u assign me this?

**Comment by ank1traj** [comment]
Assign me this issue.

**Comment by himanshusharma89** [comment]
I would like to work on this in C and C++ language.

**Comment by Marcus-auz** [comment]
can work on c++ ,assign me
