### ISSUE TITLE
Implementing Insertion, Deletion in a Stack

### ISSUE THREAD

**Issue by dibyendu415** [JGEC-Winter-of-Code/JWoC_Algorithms#23]

**Comment by SubhradeepSS** [comment]
I made a PR fixing this issue.
Can u assign me this?

**Comment by richard937** [comment]
@SubhradeepSS only push those codes which are mentioned

**Comment by Marcus-auz** [comment]
would like to work on c++ for the same

**Comment by richard937** [comment]
@Marcus-auz go-ahead, you can do it in python or java
