### ISSUE TITLE
Java Program to check whether the Number is Kaprekar or not

### ISSUE THREAD

**Issue by himanshusharma89** [JGEC-Winter-of-Code/JWoC_Algorithms#74]
Write a program to find the given number is Kaprekar or not. A number if kaprekar if the representation of its square can be split into two parts that add up to the original number. For instance, 45 is a Kaprekar number, because 45^2 = 2025 and 20 + 25 = 45.

**Comment by satyamroy001** [comment]
[kaprekar number.zip](https://github.com/JGEC-Winter-of-Code-JWoC/JWoC_Algorithms/files/4244815/kaprekar.number.zip)

**Comment by satyamroy001** [comment]
i solved this
